Repository School-of-Website-Engineering/STARART, pull requests merged in 2023-02, with the labels that each got.

#41 update:添加媒体查询、更新布局
  package-lock.json
  package.json
  public/index.html
  src/App.vue
  src/assets/scss/_meidia.scss
  src/assets/scss/global.scss
  src/main.js
  src/views/index/bottomMenu/index.vue
  src/views/index/event/index.vue
  src/views/index/globalStatusBar/index.vue
  src/views/index/index.vue
  src/views/index/shortcutBar/index.vue
  src/views/index/textOutput/index.vue
Labels: enhancement

#42 chore(main): release 1.1.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#45 chore(main): release 1.1.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#46 增加sys
  src/App.vue
  src/utils/buffSys.js
  src/utils/foodSys.js
  src/utils/hpSys.js
  src/views/index/shortcutBar/index.vue
Labels: dependencies

#47 feat:兼容各设备屏幕大小
  src/App.vue
  src/assets/scss/_media.scss
  src/assets/scss/_meidia.scss
  src/assets/scss/global.scss
  src/store/Def/index.js
  src/store/Gift/index.js
  src/store/Health/index.js
  src/store/Hungry/index.js
  src/store/Physical/index.js
  src/store/PhysicalCon/index.js
  src/views/index/bottomMenu/index.vue
  src/views/index/event/index.vue
  src/views/index/globalStatusBar/index.vue
  src/views/index/shortcutBar/index.vue
  src/views/index/textOutput/index.vue
  vue.config.js
Labels: bug, enhancement

#49 dev分支同步main分支
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: autorelease: pending, autorelease: tagged

#52 chore(main): release 1.2.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#53 chore(main): release 1.2.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#54 chore(main): release 1.2.2
  CHANGELOG.md
Labels: autorelease: pending

#57 chore(main): release 1.2.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#58 chore(main): release 1.2.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#60 chore(main): release 1.2.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#61 chore(main): release 1.2.6
  CHANGELOG.md
Labels: autorelease: pending

#62 chore(main): release 1.2.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#63 chore(main): release 1.2.8
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#67 Develop
  package-lock.json
  package.json
  src/components/isLoading/index.vue
  src/utils/buffSys.js
  src/utils/player.js
  src/views/index/bottomMenu/index.vue
  src/views/index/event/index.vue
  src/views/index/globalStatusBar/index.vue
  src/views/index/index.vue
Labels: bug, enhancement, autorelease: tagged

#69 Merge pull request #67 from School-of-Website-Engineering/develop
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement

#74 Develop
  src/assets/scss/_media.scss
  src/store/Def/index.js
  src/store/Gift/index.js
  src/store/Health/index.js
  src/store/Hungry/index.js
  src/store/Physical/index.js
  src/store/basicValue/index.js
  src/store/buff/index.js
  src/store/foods/index.js
  src/store/index.js
  src/store/player/index.js
  src/store/timeState/index.js
  src/store/timer/index.js
  src/store/weatherSys/index.js
  src/utils/buffSys.js
  src/utils/player.js
  src/views/index/bottomMenu/index.vue
  src/views/index/event/index.vue
  src/views/index/index.vue
Labels: enhancement

#75 Develop
  .eslintrc.js
  babel.config.js
  src/App.vue
  src/store/basicValue/index.js
  src/store/index.js
  src/store/timeState/index.js
  src/store/timer/index.js
  src/store/weatherSys/index.js
  src/utils/foodSys.js
  src/views/index/bottomMenu/index.vue
  src/views/index/globalStatusBar/index.vue
Labels: bug, enhancement

#76 chore(main): release 1.3.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#77 更新游戏世界时间
  src/store/timer/index.js
Labels: bug, enhancement

#78 Develop
  src/main.js
  src/store/buff/index.js
  src/store/foods/index.js
  src/store/timeState/index.js
  src/store/timer/index.js
  src/views/index/bottomMenu/index.vue
  src/views/index/event/index.vue
  src/views/index/globalStatusBar/index.vue
  src/views/index/shortcutBar/index.vue
  src/views/index/textOutput/index.vue
Labels: enhancement, invalid

#79 chore(main): release 1.3.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#80 revert:回滚故障代码，新布局制作中...
  package-lock.json
  package.json
  postcss.config.js
  src/main.js
  src/store/timer/index.js
  src/views/index/bottomMenu/index.vue
  src/views/index/event/index.vue
  src/views/index/globalStatusBar/index.vue
  src/views/index/shortcutBar/index.vue
  src/views/index/textOutput/index.vue
Labels: enhancement

#81 chore(main): release 1.3.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#82 update:更新页面布局
  src/App.vue
  src/assets/scss/_media.scss
  src/main.js
  src/views/index/bottomMenu/index.vue
  src/views/index/event/index.vue
  src/views/index/globalStatusBar/index.vue
  src/views/index/shortcutBar/index.vue
  src/views/index/textOutput/index.vue
Labels: bug, documentation, enhancement, dependencies

#83 chore(main): release 1.3.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#84 更新页面布局
  src/assets/scss/_media.scss
  src/components/isLoading/index.vue
  src/main.js
  src/views/index/shortcutBar/index.vue
  src/views/index/textOutput/index.vue
Labels: enhancement

#85 完成50%布局
  src/assets/scss/_media.scss
  src/main.js
  src/views/index/bottomMenu/index.vue
  src/views/index/event/index.vue
  src/views/index/globalStatusBar/index.vue
  src/views/index/shortcutBar/index.vue
  src/views/index/textOutput/index.vue
Labels: enhancement

#86 更新页面布局
  src/assets/scss/_media.scss
  src/assets/scss/_reset.scss
  src/main.js
  src/store/timer/index.js
  src/views/index/bottomMenu/index.vue
  src/views/index/event/index.vue
  src/views/index/globalStatusBar/index.vue
  src/views/index/shortcutBar/index.vue
  src/views/index/textOutput/index.vue
Labels: enhancement

#87 fix:修复加载动画快捷栏层级
  src/views/index/shortcutBar/index.vue
Labels: bug, documentation, enhancement

#88 chore(main): release 1.3.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#90 同步发布分支main => dev
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: duplicate, autorelease: tagged

#91 Develop
  src/main.js
  src/views/bubbleDialog/index.vue
  src/views/index/bottomMenu/index.vue
  src/views/index/components/channel-edit.vue
  src/views/index/event/index.vue
  src/views/index/shortcutBar/index.vue
Labels: bug, enhancement

#92 更新页面布局
  src/main.js
  src/store/index.js
  src/store/mapEventName/index.js
  src/views/bubbleDialog/index.vue
  src/views/index/bottomMenu/index.vue
  src/views/index/components/channel-edit.vue
  src/views/index/components/exploreNotes.vue
  src/views/index/event/index.vue
  src/views/index/shortcutBar/index.vue
  src/views/openMap/index.vue
Labels: bug, documentation, enhancement, question, autorelease: tagged

#93 Develop
  src/assets/scss/global.scss
  src/store/mapEventName/index.js
  src/store/timer/index.js
  src/store/weatherSys/index.js
  src/utils/flash.js
  src/views/index/bottomMenu/index.vue
  src/views/index/components/exploreNotes.vue
  src/views/index/globalStatusBar/index.vue
  src/views/index/textOutput/index.vue
Labels: bug, documentation, enhancement

#95 Readme.md Update
  README.md
  src/utils/flash.js
  src/views/index/textOutput/index.vue
Labels: enhancement

#96 更新生存评估期--第1天到第7天事件
  src/store/runGroupEvent/index.js
  src/store/timer/index.js
  src/views/index/bottomMenu/index.vue
  src/views/index/globalStatusBar/index.vue
  src/views/index/textOutput/index.vue
  vue.config.js
Labels: enhancement

#97 添加当前时间状态
  src/store/timeState/index.js
  src/store/timer/index.js
  src/views/index/bottomMenu/index.vue
Labels: enhancement

#98 更新暂停游戏与开始
  src/store/timer/index.js
  src/views/index/bottomMenu/index.vue
Labels: enhancement, autorelease: tagged

#99 Develop
  CHANGELOG.md
  CONTRIBUTING.md
  package-lock.json
  package.json
  src/store/player/index.js
  src/store/timer/index.js
  src/views/index/globalStatusBar/index.vue
  src/views/index/textOutput/index.vue
Labels: enhancement

#100 refactor:使用vuex传递数据以便与后端交互，性能优化
  src/store/index.js
  src/store/mapEvent/index.js
  src/store/mapEventName/index.js
  src/views/index/components/exploreNotes.vue
  src/views/index/event/index.vue
  src/views/index/textOutput/index.vue
Labels: bug, enhancement

#101 chore(main): release 1.3.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#104 chore(main): release 1.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#105 Dev
  public/index.html
  src/assets/bag.png
  src/assets/bag.svg
  src/assets/bagClick.png
  src/assets/bagClick.svg
  src/main.js
  src/router/routes.js
  src/store/timer/index.js
  src/views/index/bottomMenu/index.vue
  src/views/index/components/bubbleDialog/index.vue
  src/views/index/components/dialog.vue
  src/views/index/components/exploreNotes.vue
  src/views/index/event/index.vue
  src/views/index/globalStatusBar/index.vue
  src/views/index/shortcutBar/index.vue
  src/views/openMap/index.vue
Labels: enhancement

#106 Develop
  src/App.vue
  src/api/index.js
  src/assets/scss/_media.scss
  src/components/isLoading/index.vue
  src/main.js
  src/router/index.js
  src/router/routes.js
  src/utils/request.js
  src/views/index/bottomMenu/index.vue
  src/views/index/components/bubbleDialog/index.vue
  src/views/index/event/index.vue
  src/views/index/globalStatusBar/index.vue
Labels: bug, enhancement

#107 chore(main): release 1.4.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#108 Develop
  src/App.vue
  src/assets/scss/global.scss
  src/main.js
  src/store/exploreNotes/index.js
  src/store/index.js
  src/views/index/bottomMenu/index.vue
  src/views/index/components/bubbleDialog.vue
  src/views/index/components/dialog.vue
  src/views/index/components/eventMap.vue
  src/views/index/components/exploreNotes.vue
  src/views/index/event/index.vue
  src/views/index/event/tes.vue
Labels: enhancement

#109 main=>dev
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: autorelease: tagged

#110 合并JS报错界面V2
  public/index.html
Labels: 最高优先级

#113 Develop
  public/index.html
  src/store/backpack/index.js
  src/views/index/bottomMenu/index.vue
  src/views/index/event/index.vue
Labels: bug
